# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pomadgw's blog
email: rahadian.y@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog at github;
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pomadgw.github.io" # the base hostname & protocol for your site
twitter_username: RianYusuf94
github_username:  pomadgw
timezone: Asia/Jakarta

# Build settings
markdown: kramdown
gems:
- jekyll-compass
- jekyll-paginate
- octopress-autoprefixer

permalink: :year/:month/:day/:title.html

excerpt_separator: '<!-- more -->'

exclude: ['bin', 'vendor']

sass:
  style: compressed

paginate: 10

paginate_path: "/blog/page/:num/"

highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      # layout: "default"
      is_index: false
# jekyll-archives:
#   enabled: 'all'
#   layout: 'archives'
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'
